# Generated by Django 5.0.1 on 2024-02-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=360, unique=True)),
                ('telefone', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
