# Generated by Django 5.0.1 on 2024-02-01 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("igrejas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="igreja",
            options={"ordering": ["nome"]},
        ),
    ]
