# Generated by Django 5.0.1 on 2024-02-01 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pessoas", "0002_remove_clero_endereco_remove_funcionario_endereco_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batismo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                (
                    "batizado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batismos_batizado",
                        to="pessoas.paroquiano",
                    ),
                ),
                (
                    "celebrante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batismos_celebrante",
                        to="pessoas.clero",
                    ),
                ),
                (
                    "padrinho1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batismos_padrinho1",
                        to="pessoas.paroquiano",
                    ),
                ),
                (
                    "padrinho2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batismos_padrinho2",
                        to="pessoas.paroquiano",
                    ),
                ),
            ],
            options={
                "ordering": ["batizado"],
            },
        ),
    ]
