# Generated by Django 5.0.1 on 2024-02-01 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geral", "0001_initial"),
        ("pessoas", "0002_remove_clero_endereco_remove_funcionario_endereco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enderecofuncionario",
            name="funcionario",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pessoas.funcionario",
            ),
            preserve_default=False,
        ),
    ]
