# Generated by Django 5.0.1 on 2024-02-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geral', '0001_initial'),
        ('igrejas', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecoclero',
            name='clero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoas.clero'),
        ),
        migrations.AddField(
            model_name='enderecofuncionario',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoas.funcionario'),
        ),
        migrations.AddField(
            model_name='enderecoigreja',
            name='igreja',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='igrejas.igreja'),
        ),
        migrations.AddField(
            model_name='enderecoparoquiano',
            name='paroquiano',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoas.paroquiano'),
        ),
    ]
