# Generated by Django 5.0.1 on 2024-02-01 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geral", "0002_enderecofuncionario_funcionario"),
        ("pessoas", "0002_remove_clero_endereco_remove_funcionario_endereco_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnderecoClero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=8)),
                ("logradouro", models.CharField(max_length=200)),
                ("numero", models.CharField(max_length=15)),
                ("complemento", models.CharField(max_length=100)),
                ("bairro", models.CharField(max_length=360)),
                ("cidade", models.CharField(max_length=360)),
                ("estado", models.CharField(max_length=360)),
                (
                    "funcionario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="pessoas.clero"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnderecoParoquiano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=8)),
                ("logradouro", models.CharField(max_length=200)),
                ("numero", models.CharField(max_length=15)),
                ("complemento", models.CharField(max_length=100)),
                ("bairro", models.CharField(max_length=360)),
                ("cidade", models.CharField(max_length=360)),
                ("estado", models.CharField(max_length=360)),
                (
                    "funcionario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pessoas.paroquiano",
                    ),
                ),
            ],
        ),
    ]
