# Generated by Django 5.0.1 on 2024-02-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geral", "0002_funcoesclero"),
        ("pessoas", "0002_alter_clero_options_alter_funcionario_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funcoesclero",
            options={"ordering": ["nome"], "verbose_name_plural": "Funções Clero"},
        ),
        migrations.AlterModelOptions(
            name="funcoesfuncionarios",
            options={
                "ordering": ["nome"],
                "verbose_name_plural": "Funções Funcionários",
            },
        ),
        migrations.CreateModel(
            name="EnderecoFuncionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=8)),
                ("logradouro", models.CharField(max_length=200)),
                ("numero", models.CharField(max_length=15)),
                ("complemento", models.CharField(max_length=100)),
                ("bairro", models.CharField(max_length=360)),
                ("cidade", models.CharField(max_length=360)),
                ("estado", models.CharField(max_length=360)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pessoas.funcionario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Endereços Funcionários",
            },
        ),
    ]
