# Generated by Django 5.0.1 on 2024-02-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geral", "0003_alter_funcoesclero_options_and_more"),
        ("pessoas", "0002_alter_clero_options_alter_funcionario_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enderecofuncionario",
            options={},
        ),
        migrations.AlterField(
            model_name="enderecofuncionario",
            name="funcionario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="pessoas.funcionario"
            ),
        ),
    ]
