# Generated by Django 5.0.1 on 2024-02-01 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clero",
            options={"ordering": ["nome"], "verbose_name_plural": "Clero"},
        ),
        migrations.AlterModelOptions(
            name="funcionario",
            options={"ordering": ["nome"], "verbose_name_plural": "Funcionarios"},
        ),
        migrations.AlterModelOptions(
            name="paroquiano",
            options={"ordering": ["nome"], "verbose_name_plural": "Paroquianos"},
        ),
    ]
