# Generated by Django 5.0.1 on 2024-01-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="data_nascimento",
            field=models.DateField(),
        ),
    ]
