# Generated by Django 5.0.1 on 2024-02-01 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clero",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="paroquiano",
            name="endereco",
        ),
    ]
