# Generated by Django 5.0.1 on 2024-01-30 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geral", "0001_initial"),
        ("pessoas", "0005_funcionario_delete_pessoa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="funcao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geral.funcoesfuncionarios",
            ),
        ),
    ]
