# Generated by Django 5.0.1 on 2024-01-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("igrejas", "0001_initial"),
        ("pessoas", "0010_clero_igreja_funcionario_igreja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clero",
            name="igreja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="igrejas.igreja"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="igreja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="igrejas.igreja"
            ),
        ),
    ]
