# Generated by Django 5.0.1 on 2024-01-30 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("igrejas", "0001_initial"),
        ("pessoas", "0011_alter_clero_igreja_alter_funcionario_igreja"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paroquiano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=360)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                (
                    "genero",
                    models.CharField(
                        choices=[("F", "Feminino"), ("M", "Masculino")], max_length=1
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("data_nascimento", models.DateField()),
                ("batizado", models.BooleanField(default=False)),
                (
                    "igreja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="igrejas.igreja"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
